services:

  db: 
    ports:
      - 15432:5432

  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    image: arianashafiee/choreo-tool:dev
    env_file:
      - .server.dev.env
    volumes:
      - ./server/src:/usr/src/app/src
    