services:

  db:
    image: postgres:17-alpine
    ports:
      - 15432:5432
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build:
      context: server
      dockerfile: dev.Dockerfile
    image: arianashafiee/cheer-tool:dev
    env_file:
      - .server.dev.env
    volumes:
      - ./server/src:/usr/src/app/src
    