services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 30s
      start_interval: 3s
      timeout: 10s

  server:
    build: server
    restart: unless-stopped
    env_file:
      - .env
      - .server.env
    environment:
      - DB_HOST=db
    ports:
      - 3000:3000
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      db:
        condition: service_healthy
        restart: true